// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCws1gD0Xpw109GBhJq_81GHEZwr9a5No',
    appId: '1:799870452533:web:a93d4528882127bd9ec27c',
    messagingSenderId: '799870452533',
    projectId: 'beauty-saloon-app-41e85',
    authDomain: 'beauty-saloon-app-41e85.firebaseapp.com',
    storageBucket: 'beauty-saloon-app-41e85.appspot.com',
    measurementId: 'G-D2HG7W0HGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdDIDsXrMmAoxa_kJaOLeABtTAhQB0BCM',
    appId: '1:799870452533:android:71dd867099698e6e9ec27c',
    messagingSenderId: '799870452533',
    projectId: 'beauty-saloon-app-41e85',
    storageBucket: 'beauty-saloon-app-41e85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9YNyEw6pgabK04HeEbrI9QihMLOMWxhA',
    appId: '1:799870452533:ios:798659a0ef50ced59ec27c',
    messagingSenderId: '799870452533',
    projectId: 'beauty-saloon-app-41e85',
    storageBucket: 'beauty-saloon-app-41e85.appspot.com',
    iosClientId: '799870452533-ln1pdciu78rb8bhut8685f61nrcvmlp8.apps.googleusercontent.com',
    iosBundleId: 'com.santosenoque.booking',
  );
}
